### ISSUE TITLE
PostSharp index build slow on bitbucket

### ISSUE THREAD

**Issue by ekmedinet** [postsharp/PostSharp.IL#10]
Hello,

When I do docker build in bitbucket environment, it takes PostSharp long time to build index (10-20 minutes). However when building the same docker image locally, it is quick, like 500 seconds vs 5 seconds. Why it can be so slow in bitbucket? This is the part of build log:

`#19 28.75          Executing "/usr/share/dotnet/dotnet" exec --roll-forward Minor obj/Release/net6.0/PostSharp/PostSharp.Compiler.Hosting.CommandLine.dll /path /usr/share/dotnet/sdk/6.0.427/Microsoft/Microsoft.NET.Build.Extensions/net461/lib /path /usr/share/dotnet/sdk/6.0.427/Microsoft/Microsoft.NET.Build.Extensions/net471/lib /path /usr/share/dotnet/sdk/6.0.427/Microsoft/Microsoft.NET.Build.Extensions/net462/lib /path /usr/share/dotnet/sdk/6.0.427/Microsoft/Microsoft.NET.Build.Extensions/net47/lib /P:NetCoreRootOverride=/usr/share/dotnet/ /ctdir /root/.nuget/packages/postsharp/6.10.16/build obj/Release/net6.0/Before-PostSharp/NewtonHealth.Clinical.Logic.dll /src/NewtonHealth.Clinical.Logic/obj/Release/net6.0/PostSharp/postsharp.config /NoLogo /dbin /var/tmp/postsharp /dcch /var/tmp/postsharp/cache /dspl /var/tmp/postsharp/spool /dcfg /etc/postsharp /ducfg /root/.config/postsharp /dtmp /var/tmp/postsharp/temp /dlog /var/tmp/postsharp/logs /ddep /var/tmp/postsharp/NuGetFallback /cancel:Local\postsharp-cancel-095b1b24-f38f-448b-85a0-9f40180b44c3
#19 30.42          POSTSHARP : message PS0220: PostSharp needs to generate the type index for the reference platform "{Framework=.NETCoreApp,Version=v6.0, ProcessorArchitecture=None, TypeIndexBase=.NETCoreApp,Version=v6.0, TargetingPacksId=fc68c779702900dfba2c873484942e99, RuntimeFrameworksId=79a8c31f730970dae78ba39a1339cf3f}". This could take a few seconds. The result will be cached and the next build will be faster.
#19 30.54          POSTSHARP : message PS0220: PostSharp needs to generate the type index for the runtime platform "{Framework=.NETCoreApp,Version=v6.0, ProcessorArchitecture=None, TypeIndexBase=.NETCoreApp,Version=v6.0, TargetingPacksId=fc68c779702900dfba2c873484942e99, RuntimeFrameworksId=79a8c31f730970dae78ba39a1339cf3f}". This could take a few seconds. The result will be cached and the next build will be faster.
#19 565.7          POSTSHARP : info : PostSharp 6.10.16 [PostSharp.Compiler.Hosting.CommandLine.dll 6.10.16 release | .NET 6.0.35 (X64)] complete -- 0 errors, 0 warnings, processed in 536710 ms`

I am just not sure what is going on and how to pinpoint the issue. What is going on during this index build? Is this RAM, Disk IO or CPU issue of bitbucket? Would upgrading to Metalama alleviate this issue?

**Comment by addabis** [comment]
Hello,

PostSharp restores its dependencies for every combination of Sdk, runtime, and platform into a private package store. This is necessary because PostSharp can be (and usually is) running under a different runtime than your projects' target frameworks.

Since you are using docker, this happens for every instance of your image and can lead to a download of ~1 GB of packages, which may be the bottleneck.

There are two ways to mitigate this:
1) Build a simple dotnet project with PostSharp when creating your image. This forces PostSharp to download all, or most of the packages and will not be done on subsequent builds.
2) Change the `PostSharpDependencyDirectory` MSBuild variable (you can set this as an environment variable) to point to the default NuGet package directory, usually `~/.nuget/packages` on Linux (you'd have to verify this for your particular image). This will force PostSharp to reuse packages already downloaded within the image. This should be safe to do in a Docker environment.

Of course, you can combine both for the best result, if possible (i.e. shorter image build time and smaller image size).

**Comment by ekmedinet** [comment]
Thanks for reply, don't think however that it has to do with downloads..

We ended up building the project before docker build and copy binaries into docker. For some reason this problem happened only during build inside docker.

**Comment by addabis** [comment]
No problem. We have encountered problems with dependency restore in the past.  Please let us know if you happen to have more info.
